"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { getCurrentProfile } from "@/services/profiles";

export type TransactState = { error: string } | undefined;

const serviceRequestSchema = z.object({
  serviceId: z.string().uuid("Choose a service"),
  title: z.string().trim().min(1, "Give the request a title").max(200),
  description: z.string().trim().max(2000).optional(),
});

// A client submits a service request from the Transact tab. The request is
// created under the caller's own session (RLS enforces origin='client', their
// own client_id, and no pre-assigned provider), then routed to a matching
// Service Partner via the admin client -- routing is a privileged operation the
// client cannot perform themselves.
export async function submitServiceRequest(
  _prev: TransactState,
  formData: FormData,
): Promise<TransactState> {
  const profile = await getCurrentProfile();
  if (!profile) return { error: "Not authenticated" };
  if (profile.user_type !== "client") return { error: "Only clients can submit requests." };

  const parsed = serviceRequestSchema.safeParse({
    serviceId: formData.get("serviceId"),
    title: formData.get("title"),
    description: formData.get("description") || undefined,
  });
  if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Invalid input" };

  const supabase = await createClient();
  const { data: client } = await supabase.from("clients").select("id").maybeSingle();
  if (!client) return { error: "No client account is linked to your profile." };

  const { data: request, error } = await supabase
    .from("service_requests")
    .insert({
      // reference is generated by the set_request_reference trigger.
      reference: "",
      origin: "client",
      client_id: client.id,
      service_id: parsed.data.serviceId,
      title: parsed.data.title,
      description: parsed.data.description ?? null,
    })
    .select("id,reference")
    .single();

  if (error || !request) return { error: error?.message ?? "Could not submit the request." };

  // Route to a matching Service Partner. A failure here is not fatal: the
  // request simply stays awaiting assignment for staff to place.
  try {
    await createAdminClient().rpc("route_request", { p_request_id: request.id });
  } catch {
    /* left awaiting assignment */
  }

  revalidatePath("/dashboard");
  redirect(`/dashboard/transact?submitted=${encodeURIComponent(request.reference)}`);
}
