-- Sales opportunity foundation
--
-- Establishes the client-owned sales pipeline source of truth used by the
-- future Pipeline and Bookings views. An opportunity may exist without a PO;
-- the PO relationship arrives in a later migration. Providers and staff do
-- not receive table access. Future provider invoice/payment actions must use
-- narrow SECURITY DEFINER functions instead of broad table grants.

-- ---------------------------------------------------------------------------
-- Controlled reference data and lifecycle enums
-- ---------------------------------------------------------------------------

create type public.opportunity_payment_status as enum ('unpaid', 'paid');

create type public.opportunity_event_type as enum (
  'created',
  'updated',
  'category_changed',
  'booked',
  'invoice_updated',
  'payment_changed',
  'deleted'
);

create type public.opportunity_actor_type as enum (
  'client',
  'service_provider',
  'staff',
  'system'
);

create table public.opportunity_sources (
  code          text primary key check (code ~ '^[a-z][a-z0-9_]*$'),
  name          text not null unique,
  description   text,
  display_order integer not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.opportunity_sources is
  'Controlled acquisition sources available to client sales opportunities.';

create table public.forecast_categories (
  code          text primary key check (code ~ '^[a-z][a-z0-9_]*$'),
  name          text not null unique,
  description   text,
  display_order integer not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.forecast_categories is
  'Controlled forecast labels. Display order is presentational, not a permitted-transition hierarchy.';

insert into public.opportunity_sources (code, name, description, display_order)
values
  ('team', 'Team', 'Opportunity generated by the client''s team or on-the-ground activity.', 10),
  ('web', 'Web', 'Opportunity generated by the client''s website or online channels.', 20);

insert into public.forecast_categories (code, name, description, display_order)
values
  ('open', 'Open', null, 10),
  ('upside', 'Upside', 'Deal with a realistic chance of closing in the current quarter.', 20),
  ('best_case', 'Best Case', 'Moderately confident opportunity that could close if things go perfectly.', 30),
  ('commit', 'Commit', 'Highly confident deal (80–90%+ close rate), with contracts in final stages and no major risks remaining.', 40),
  ('booked', 'Booked', 'Work on the linked purchase-order submission has completed.', 50),
  ('closed', 'Closed', 'Money is in the bank.', 60);

create trigger opportunity_sources_set_updated_at
  before update on public.opportunity_sources
  for each row execute function public.set_updated_at();

create trigger forecast_categories_set_updated_at
  before update on public.forecast_categories
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Sales opportunities
-- ---------------------------------------------------------------------------

create sequence public.sales_opportunity_reference_seq;

create table public.sales_opportunities (
  id                    uuid primary key default gen_random_uuid(),
  client_id             uuid not null default public.current_client_id() references public.clients (id) on delete cascade,
  deal_reference        text not null default '' unique,
  opportunity_source    text not null references public.opportunity_sources (code) on update restrict on delete restrict,
  opportunity_name      text not null check (btrim(opportunity_name) <> ''),
  forecast_category     text not null default 'open' references public.forecast_categories (code) on update restrict on delete restrict,
  revenue               numeric(14, 2) not null default 0 check (revenue >= 0),
  currency              text not null default 'ZAR' check (currency = 'ZAR'),
  -- Expected-payment period. Early opportunities may omit all three. A client
  -- may know the year, then quarter, before it knows the exact quarter week.
  fiscal_year           smallint check (fiscal_year between 2000 and 2200),
  fiscal_quarter        smallint check (fiscal_quarter between 1 and 4),
  fiscal_week           smallint check (fiscal_week between 1 and 13),
  invoice_number        text check (invoice_number is null or btrim(invoice_number) <> ''),
  payment_status        public.opportunity_payment_status,
  booked_at             timestamptz,
  paid_at               timestamptz,
  created_by            uuid references public.profiles (id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint sales_opportunities_fiscal_hierarchy check (
    (fiscal_year is not null or (fiscal_quarter is null and fiscal_week is null))
    and (fiscal_quarter is not null or fiscal_week is null)
  ),
  constraint sales_opportunities_payment_requires_booking check (
    payment_status is null or booked_at is not null
  ),
  constraint sales_opportunities_paid_timestamp check (
    (payment_status = 'paid' and paid_at is not null)
    or (payment_status is distinct from 'paid' and paid_at is null)
  )
);

comment on table public.sales_opportunities is
  'Client-owned sales opportunities. Pipeline and Bookings are views of this same row; opportunities may exist without a PO.';
comment on column public.sales_opportunities.deal_reference is
  'Generated immutable identifier in BLB-YYYY-NNNNNN format.';
comment on column public.sales_opportunities.fiscal_week is
  'Expected-payment week within the selected fiscal quarter (1–13).';
comment on column public.sales_opportunities.booked_at is
  'Permanent timestamp of the first completed linked PO; it may never be cleared.';
comment on column public.sales_opportunities.revenue is
  'Client-entered expected revenue in ZAR. VAT inclusion semantics remain a product reporting decision.';

create index sales_opportunities_client_id_idx
  on public.sales_opportunities (client_id);
create index sales_opportunities_client_category_idx
  on public.sales_opportunities (client_id, forecast_category);
create index sales_opportunities_client_period_idx
  on public.sales_opportunities (client_id, fiscal_year, fiscal_quarter, fiscal_week);
create index sales_opportunities_booked_at_idx
  on public.sales_opportunities (booked_at)
  where booked_at is not null;
create unique index sales_opportunities_client_invoice_unique_idx
  on public.sales_opportunities (client_id, lower(invoice_number))
  where invoice_number is not null;

-- ---------------------------------------------------------------------------
-- Append-only opportunity history
-- ---------------------------------------------------------------------------

create table public.sales_opportunity_events (
  id               uuid primary key default gen_random_uuid(),
  -- Set null on a permitted pre-booking delete so the audit event survives.
  opportunity_id   uuid references public.sales_opportunities (id) on delete set null,
  client_id        uuid not null references public.clients (id) on delete cascade,
  deal_reference   text not null,
  event_type       public.opportunity_event_type not null,
  actor_id         uuid references public.profiles (id) on delete set null,
  actor_type       public.opportunity_actor_type not null,
  details          jsonb not null default '{}'::jsonb,
  created_at       timestamptz not null default now()
);

comment on table public.sales_opportunity_events is
  'Append-only audit history for material opportunity and booking lifecycle changes.';

create index sales_opportunity_events_opportunity_id_idx
  on public.sales_opportunity_events (opportunity_id, created_at desc);
create index sales_opportunity_events_client_id_idx
  on public.sales_opportunity_events (client_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Defaults, immutability and lifecycle guards
-- ---------------------------------------------------------------------------

create or replace function public.opportunity_actor_type()
returns public.opportunity_actor_type
language sql
stable
security definer
set search_path = ''
as $$
  select case public.current_user_type()
    when 'client' then 'client'::public.opportunity_actor_type
    when 'service_provider' then 'service_provider'::public.opportunity_actor_type
    when 'staff' then 'staff'::public.opportunity_actor_type
    else 'system'::public.opportunity_actor_type
  end;
$$;

create or replace function public.prepare_sales_opportunity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_client_id uuid;
  v_sequence bigint;
  v_year text;
begin
  if v_uid is not null then
    if public.current_user_type() is distinct from 'client'::public.user_type then
      raise exception 'Only client users may create sales opportunities';
    end if;

    v_client_id := public.current_client_id();
    if v_client_id is null then
      raise exception 'No client account is linked to the current profile';
    end if;
    if new.client_id is null then
      new.client_id := v_client_id;
    elsif new.client_id is distinct from v_client_id then
      raise exception 'Cannot create an opportunity for another client';
    end if;

    if nullif(btrim(new.deal_reference), '') is not null then
      raise exception 'Deal ID is generated by the system';
    end if;
    if new.invoice_number is not null
       or new.payment_status is not null
       or new.booked_at is not null
       or new.paid_at is not null then
      raise exception 'Invoice, booking and payment fields are system managed';
    end if;
    if not exists (
      select 1 from public.opportunity_sources
      where code = new.opportunity_source and active
    ) then
      raise exception 'Choose an active opportunity source';
    end if;
    if not exists (
      select 1 from public.forecast_categories
      where code = new.forecast_category and active
    ) then
      raise exception 'Choose an active forecast category';
    end if;

    -- Defaults are evaluated before BEFORE INSERT triggers. Reassert all
    -- system-owned identity fields so crafted API payloads cannot choose them.
    new.id := gen_random_uuid();
    new.created_by := v_uid;
    new.currency := 'ZAR';
    new.created_at := now();
    new.updated_at := now();
  end if;

  if nullif(btrim(new.deal_reference), '') is null then
    v_sequence := nextval('public.sales_opportunity_reference_seq');
    v_year := to_char(timezone('Africa/Johannesburg', statement_timestamp()), 'YYYY');
    new.deal_reference := 'BLB-' || v_year || '-' || lpad(v_sequence::text, 6, '0');
  end if;

  new.opportunity_name := btrim(new.opportunity_name);
  if new.invoice_number is not null then
    new.invoice_number := btrim(new.invoice_number);
  end if;
  return new;
end;
$$;

create trigger sales_opportunities_prepare
  before insert on public.sales_opportunities
  for each row execute function public.prepare_sales_opportunity();

create or replace function public.guard_sales_opportunity_lifecycle()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.id is distinct from old.id
     or new.client_id is distinct from old.client_id
     or new.deal_reference is distinct from old.deal_reference
     or new.currency is distinct from old.currency
     or new.created_by is distinct from old.created_by
     or new.created_at is distinct from old.created_at then
    raise exception 'Opportunity identity fields are immutable';
  end if;

  if old.booked_at is not null and new.booked_at is null then
    raise exception 'The permanent booking timestamp cannot be cleared';
  end if;

  if new.opportunity_source is distinct from old.opportunity_source and not exists (
    select 1 from public.opportunity_sources
    where code = new.opportunity_source and active
  ) then
    raise exception 'Choose an active opportunity source';
  end if;
  if new.forecast_category is distinct from old.forecast_category and not exists (
    select 1 from public.forecast_categories
    where code = new.forecast_category and active
  ) then
    raise exception 'Choose an active forecast category';
  end if;

  new.opportunity_name := btrim(new.opportunity_name);
  if new.invoice_number is not null then
    new.invoice_number := btrim(new.invoice_number);
  end if;
  return new;
end;
$$;

create trigger sales_opportunities_guard_lifecycle
  before update on public.sales_opportunities
  for each row execute function public.guard_sales_opportunity_lifecycle();

create or replace function public.guard_sales_opportunity_delete()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.booked_at is not null
     or old.invoice_number is not null
     or old.payment_status is not null then
    raise exception 'Booked, invoiced or payment-tracked opportunities cannot be deleted';
  end if;
  return old;
end;
$$;

create trigger sales_opportunities_guard_delete
  before delete on public.sales_opportunities
  for each row execute function public.guard_sales_opportunity_delete();

create trigger sales_opportunities_set_updated_at
  before update on public.sales_opportunities
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Event logging
-- ---------------------------------------------------------------------------

create or replace function public.log_sales_opportunity_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := (select auth.uid());
  v_actor_type public.opportunity_actor_type := public.opportunity_actor_type();
begin
  if tg_op = 'INSERT' then
    insert into public.sales_opportunity_events (
      opportunity_id, client_id, deal_reference, event_type, actor_id, actor_type, details
    ) values (
      new.id,
      new.client_id,
      new.deal_reference,
      'created',
      v_actor_id,
      v_actor_type,
      jsonb_build_object(
        'opportunity_source', new.opportunity_source,
        'opportunity_name', new.opportunity_name,
        'forecast_category', new.forecast_category,
        'revenue', new.revenue,
        'currency', new.currency,
        'fiscal_year', new.fiscal_year,
        'fiscal_quarter', new.fiscal_quarter,
        'fiscal_week', new.fiscal_week
      )
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    insert into public.sales_opportunity_events (
      opportunity_id, client_id, deal_reference, event_type, actor_id, actor_type, details
    ) values (
      old.id,
      old.client_id,
      old.deal_reference,
      'deleted',
      v_actor_id,
      v_actor_type,
      jsonb_build_object('opportunity_name', old.opportunity_name)
    );
    return old;
  end if;

  if new.forecast_category is distinct from old.forecast_category then
    insert into public.sales_opportunity_events (
      opportunity_id, client_id, deal_reference, event_type, actor_id, actor_type, details
    ) values (
      new.id, new.client_id, new.deal_reference, 'category_changed', v_actor_id, v_actor_type,
      jsonb_build_object('before', old.forecast_category, 'after', new.forecast_category)
    );
  end if;

  if new.booked_at is distinct from old.booked_at and new.booked_at is not null then
    insert into public.sales_opportunity_events (
      opportunity_id, client_id, deal_reference, event_type, actor_id, actor_type, details
    ) values (
      new.id, new.client_id, new.deal_reference, 'booked', v_actor_id, v_actor_type,
      jsonb_build_object('booked_at', new.booked_at)
    );
  end if;

  if new.invoice_number is distinct from old.invoice_number then
    insert into public.sales_opportunity_events (
      opportunity_id, client_id, deal_reference, event_type, actor_id, actor_type, details
    ) values (
      new.id, new.client_id, new.deal_reference, 'invoice_updated', v_actor_id, v_actor_type,
      jsonb_build_object('before', old.invoice_number, 'after', new.invoice_number)
    );
  end if;

  if new.payment_status is distinct from old.payment_status
     or new.paid_at is distinct from old.paid_at then
    insert into public.sales_opportunity_events (
      opportunity_id, client_id, deal_reference, event_type, actor_id, actor_type, details
    ) values (
      new.id, new.client_id, new.deal_reference, 'payment_changed', v_actor_id, v_actor_type,
      jsonb_build_object(
        'before', jsonb_build_object('status', old.payment_status, 'paid_at', old.paid_at),
        'after', jsonb_build_object('status', new.payment_status, 'paid_at', new.paid_at)
      )
    );
  end if;

  if new.opportunity_source is distinct from old.opportunity_source
     or new.opportunity_name is distinct from old.opportunity_name
     or new.revenue is distinct from old.revenue
     or new.fiscal_year is distinct from old.fiscal_year
     or new.fiscal_quarter is distinct from old.fiscal_quarter
     or new.fiscal_week is distinct from old.fiscal_week then
    insert into public.sales_opportunity_events (
      opportunity_id, client_id, deal_reference, event_type, actor_id, actor_type, details
    ) values (
      new.id,
      new.client_id,
      new.deal_reference,
      'updated',
      v_actor_id,
      v_actor_type,
      jsonb_build_object(
        'before', jsonb_build_object(
          'opportunity_source', old.opportunity_source,
          'opportunity_name', old.opportunity_name,
          'revenue', old.revenue,
          'fiscal_year', old.fiscal_year,
          'fiscal_quarter', old.fiscal_quarter,
          'fiscal_week', old.fiscal_week
        ),
        'after', jsonb_build_object(
          'opportunity_source', new.opportunity_source,
          'opportunity_name', new.opportunity_name,
          'revenue', new.revenue,
          'fiscal_year', new.fiscal_year,
          'fiscal_quarter', new.fiscal_quarter,
          'fiscal_week', new.fiscal_week
        )
      )
    );
  end if;

  return new;
end;
$$;

create trigger sales_opportunities_log_event
  after insert or update on public.sales_opportunities
  for each row execute function public.log_sales_opportunity_event();

create trigger sales_opportunities_log_delete
  before delete on public.sales_opportunities
  for each row execute function public.log_sales_opportunity_event();

-- ---------------------------------------------------------------------------
-- Row-level security and grants
-- ---------------------------------------------------------------------------

alter table public.opportunity_sources enable row level security;
alter table public.forecast_categories enable row level security;
alter table public.sales_opportunities enable row level security;
alter table public.sales_opportunity_events enable row level security;

create policy opportunity_sources_select_active on public.opportunity_sources
  for select to authenticated
  using (active);

create policy forecast_categories_select_active on public.forecast_categories
  for select to authenticated
  using (active);

create policy sales_opportunities_select_own on public.sales_opportunities
  for select to authenticated
  using (client_id = public.current_client_id());

create policy sales_opportunities_insert_own on public.sales_opportunities
  for insert to authenticated
  with check (client_id = public.current_client_id());

create policy sales_opportunities_update_own on public.sales_opportunities
  for update to authenticated
  using (client_id = public.current_client_id())
  with check (client_id = public.current_client_id());

create policy sales_opportunities_delete_pre_booking on public.sales_opportunities
  for delete to authenticated
  using (
    client_id = public.current_client_id()
    and booked_at is null
    and invoice_number is null
    and payment_status is null
  );

create policy sales_opportunity_events_select_own on public.sales_opportunity_events
  for select to authenticated
  using (client_id = public.current_client_id());

grant select on public.opportunity_sources to authenticated;
grant select on public.forecast_categories to authenticated;

grant select, insert, delete on public.sales_opportunities to authenticated;
grant update (
  opportunity_source,
  opportunity_name,
  forecast_category,
  revenue,
  fiscal_year,
  fiscal_quarter,
  fiscal_week
) on public.sales_opportunities to authenticated;
grant select on public.sales_opportunity_events to authenticated;

grant all on public.opportunity_sources to service_role;
grant all on public.forecast_categories to service_role;
grant all on public.sales_opportunities to service_role;
grant all on public.sales_opportunity_events to service_role;
grant usage, select on sequence public.sales_opportunity_reference_seq to service_role;

revoke execute on function public.opportunity_actor_type() from public;
revoke execute on function public.prepare_sales_opportunity() from public;
revoke execute on function public.guard_sales_opportunity_lifecycle() from public;
revoke execute on function public.guard_sales_opportunity_delete() from public;
revoke execute on function public.log_sales_opportunity_event() from public;
